from pathlib import Path

p = Path('BABA_BOT_RESEARCH_RESULTS_REGISTRY.md')
text = p.read_text()
marker = '# REGIME DETECTOR FOUNDATION\n'
entry = '''# B27BM — 24H SIDEWAYS Age-Hazard Audit\n\n**Source:** `BTC_24H_SIDEWAYS_AGE_HAZARD_B27BM_Result.md`\n\n**Audit:** PASS. **Frozen verdict: `B27BM_PHASED_SIDEWAYS_HAZARD_SUPPORTED`.**\n\n**Purpose:** test whether SIDEWAYS has a reproducible age-dependent cause-specific exit structure, conditional on the episode still being SIDEWAYS. No trading direction or economics were used.\n\n**Exact parent identity:** 1,023 B27BH bracketed SIDEWAYS episodes = 527 RESUME + 496 TRANSITION; BULL-origin 532; BEAR-origin 491.\n\n### Pooled-OOS primary hazard readout\n\n- BULL age1 / 4h: RESUME **28.8%**, TRANSITION **13.7%**, survive **57.5%**; T-R **-15.0pp**.\n- BULL age2 / 8h: RESUME **20.0%**, TRANSITION **25.0%**, survive **55.0%**; T-R **+5.0pp**.\n- BULL age3 / 12h: RESUME **13.1%**, TRANSITION **22.2%**, survive **64.6%**; T-R **+9.1pp**.\n- BEAR age1 / 4h: RESUME **25.2%**, TRANSITION **20.7%**, survive **54.1%**; T-R **-4.5pp**.\n- BEAR age2 / 8h: RESUME **19.1%**, TRANSITION **40.5%**, survive **40.5%**; T-R **+21.4pp**.\n- BEAR age3 / 12h: RESUME **20.8%**, TRANSITION **30.2%**, survive **49.1%**; T-R **+9.4pp**.\n\n**OOS stability:** age1->age2 transition-minus-resume margin shifted upward in every preregistered cell: external BULL -17.8pp->-0.9pp; external BEAR -7.4pp->+10.6pp; validation BULL -12.0pp->+13.5pp; validation BEAR -2.2pp->+32.3pp. All frozen gates passed.\n\n**Interpretation:** SIDEWAYS is not temporally homogeneous. The first 4h bar is continuation-heavy; the 8h-12h phase becomes transition-heavy. Ages 4-6 are descriptive only and do not justify a monotonic older-SIDEWAYS=more-reversal rule. This supports an age-dependent regime-state concept only; it does not define a production state machine or trading rule.\n\nObservable CI: run `32619094283`, job `97144386776`, success; exact hazard CSV artifact `9487827397`.\n\nResearch only. Live BBC unchanged.\n\n---\n\n'''
if '# B27BM — 24H SIDEWAYS Age-Hazard Audit' not in text:
    if marker not in text:
        raise SystemExit('registry marker not found')
    text = text.replace(marker, marker + '\n' + entry, 1)
    p.write_text(text)
